let myDate = new Date()
console.log(myDate.toString())
console.log(myDate.toDateString())
console.log(myDate.toLocaleString())
console.log(typeof myDate)
let myCreatedDate =  new Date(2023, 0 ,23)
console.log(myCreatedDate.toDateString())
let TimeStamp = Date.now()
console.log(TimeStamp)
let creatdate = new Date("01-05-2025")
console.log(creatdate.getTime())
console.log(Math.floor(Date.now()/1000))
let newDate = new Date()
console.log(newDate)
console.log(newDate.getMonth()+1)
console.log(newDate.getDay())
newDate.toLocaleString('Default',{
    weekday:"long"
})